[package]
name = "apollo-smith"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Coenen <benjamin.coenen@apollographql.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/apollographql/apollo-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-encoder = { path = "../apollo-encoder" }
arbitrary = { version = "1.0.3", features = ["derive"] }
once_cell = "1.9.0"
